// Generated by https://quicktype.io

export interface FavoriteResponse {
    media_type: string;
    media_id:   number;
    favorite:   boolean;
}

export interface FavoriteMoviesResponse {
    page:          number;
    results:       FavoriteMovie[];
    total_pages:   number;
    total_results: number;
}

export interface FavoriteMovie {
    original_language: string;
    original_title:    string;
    poster_path:       string;
    title:             string;
    video:             boolean;
    vote_average:      number;
    id:                number;
    release_date:      string;
    vote_count:        number;
    adult:             boolean;
    backdrop_path:     string;
    overview:          string;
    genre_ids:         number[];
    popularity:        number;
}
